### ISSUE TITLE
ModuleNotFoundError: No module named 'index_max'

### ISSUE THREAD

**Issue by ldepn** [lijx10/USIP#12]
I have run "
cd models/index_max_ext
python3 setup.py install" 
and 
"cd models/ball_query_ext
python3 setup.py install",
but when i run  "train_detector.py" in KITTI dir, a bug is show "ModuleNotFoundError: No module named 'index_max'"
how to fix it?

**Comment by lijx10** [comment]
Could you double check whether the index_max is successfully compiled and install?
