### ISSUE TITLE
Running on own point clouds

### ISSUE THREAD

**Issue by Limzui** [lijx10/USIP#18]
Hi, firstly thank you for your great work on your paper as well as releasing the code. 

I would like to know how to run a pretrained model on my own point clouds. More specifically, how do I obtain the surface normals and curvature inputs to the detector network (anc_sn)?

**Comment by lijx10** [comment]
The surface normal and curvature can be acquired by PCL, a point cloud processing library, i.e., NormalEstimation, PrincipleCurvaturesEstimation. 
When re-training the networks with your own data, it is not necesary to input surface normal or curvature. Those are optional.
