### ISSUE TITLE
weights and evaluation code.

### ISSUE THREAD

**Issue by rAm1n** [lijx10/USIP#3]
Hi @lijx10 
Thanks very much for sharing the code. I was wondering if It would be possible for you to share the weights too? I am facing a little difficulty while training the model on KITTI dataset and I get negative loss. I would also highly appreciate if you could share the evaluation code too.

Thanks

**Comment by lijx-nutonomy** [comment]
The evaluation codes are released just now. There is a link to Google Drive that contains trained model for oxford. We didn't train on Kitti, the kitti results are generated with oxford models.

Negative loss is normal because the design of the loss allows negative values.

**Comment by rAm1n** [comment]
That's awesome! thanks very much.
