### ISSUE TITLE
PCLKeypoint

### ISSUE THREAD

**Issue by XuyangBai** [lijx10/USIP#4]
Thanks for your sharing. I read the code in `save_keypoints.py` and find that you use `PCLKeypoint` library to do the hand-crafted method detection.  But I cannot find this library on Google, could you please share the website ?

**Comment by lijx10** [comment]
PCLKeypoints are uploaded to: https://github.com/lijx10/PCLKeypoints. This is a python wrapper over PCL detectors. Run `python setup install` to install it.

**Comment by XuyangBai** [comment]
Thank you so much for your sharing!
