### ISSUE TITLE
Is the curvature used?

### ISSUE THREAD

**Issue by XuyangBai** [lijx10/USIP#7]
Hi @lijx10, I was trying  to calculate the repeatability for KITTI dataset.  I found that in `kitti_test_loader.py` the input to detector contains the surface normal (sn_x, sn_y, sn_z and curvature). But in `kitti_test_prepare.m`, I think you doesn't save the curvature in file, so I wonder in which step do you calculate the curvature?  And how do you generate the npy file in the folder `np_0.20_20480_r90_sn`?

**Comment by lijx10** [comment]
The curvature is computed using standard PCL python wrapper: https://github.com/strawlab/python-pcl

**Comment by XuyangBai** [comment]
Thanks a lot .
